// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_better_than_the_developer = "CgkIh8W6saADEAIQDA"; // <GPGSID>
        public const string achievement_climb_graduate = "CgkIh8W6saADEAIQCw"; // <GPGSID>
        public const string achievement_double_digits = "CgkIh8W6saADEAIQCA"; // <GPGSID>
        public const string leaderboard_highscore = "CgkIh8W6saADEAIQAA"; // <GPGSID>
        public const string achievement_getting_the_hang_of_it = "CgkIh8W6saADEAIQCQ"; // <GPGSID>
        public const string achievement_gate_of_expertise = "CgkIh8W6saADEAIQDQ"; // <GPGSID>
        public const string achievement_patience_makes_perfect = "CgkIh8W6saADEAIQCg"; // <GPGSID>

}

